import { RawCharacterRecord } from '@/types/source';

export function getWikiDatasetCharacters(): RawCharacterRecord[] {
  return [
    {
      source_id: 'wikidataset',
      source_character_id: 'luffy',
      name: 'Monkey D. Luffy',
      japanese_name: 'モンキー・D・ルフィ',
      romanized_name: 'Monkī Dī Rufi',
      aliases: ['Luffy', 'Straw Hat Luffy', 'Straw Hat Captain', 'Mugiwara', 'Joy Boy', 'Fifth Emperor'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 19,
      height: 174,
      bounty: 3000000000,
      birthday: 'May 5',
      blood_type: 'F',
      origin: 'East Blue',
      first_appearance: 'Chapter 1',
      first_arc: 'Romance Dawn',
      devil_fruit_name: 'Hito Hito no Mi, Model: Nika',
      devil_fruit_type: 'Mythical Zoan',
      devil_fruit_model: 'Nika',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Captain of the Straw Hat Pirates and one of the Four Emperors.',
      image_url: 'https://cdn.myanimelist.net/images/characters/9/310307.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'zoro',
      name: 'Roronoa Zoro',
      japanese_name: 'ロロノア・ゾロ',
      romanized_name: 'Roronoa Zoro',
      aliases: ['Zoro', 'Pirate Hunter Zoro', 'Pirate Hunter', 'Zoro-san', 'King of Hell'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 21,
      height: 181,
      bounty: 1111000000,
      birthday: 'November 11',
      blood_type: 'X',
      origin: 'East Blue',
      first_appearance: 'Chapter 3',
      first_arc: 'Romance Dawn',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Swordsman'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Master swordsman using Three Sword Style and fighter for the Straw Hats.',
      image_url: 'https://cdn.myanimelist.net/images/characters/3/100534.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'nami',
      name: 'Nami',
      japanese_name: 'ナミ',
      romanized_name: 'Nami',
      aliases: ['Cat Burglar Nami', 'Cat Burglar'],
      gender: 'Female',
      race: 'Human',
      status: 'Alive',
      age: 20,
      height: 170,
      bounty: 366000000,
      birthday: 'July 3',
      blood_type: 'X',
      origin: 'East Blue',
      first_appearance: 'Chapter 8',
      first_arc: 'Orange Town',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Navigator'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: [],
      description: 'Navigator of the Straw Hat Pirates dreaming of mapping the entire world.',
      image_url: 'https://cdn.myanimelist.net/images/characters/2/263249.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'usopp',
      name: 'Usopp',
      japanese_name: 'ウソップ',
      romanized_name: 'Usoppu',
      aliases: ['God Usopp', 'Sogeking', 'King of Snipers'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 19,
      height: 176,
      bounty: 500000000,
      birthday: 'April 1',
      blood_type: 'S',
      origin: 'East Blue',
      first_appearance: 'Chapter 23',
      first_arc: 'Syrup Village',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Sniper'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: ['Observation'],
      description: 'Sniper of the Straw Hat Pirates and courageous warrior of the sea.',
      image_url: 'https://cdn.myanimelist.net/images/characters/14/100418.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'sanji',
      name: 'Vinsmoke Sanji',
      japanese_name: 'ヴィンスモーク・サンジ',
      romanized_name: 'Vinsumōku Sanji',
      aliases: ['Sanji', 'Black Leg Sanji', 'Black Leg', 'Soba Mask'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 21,
      height: 180,
      bounty: 1032000000,
      birthday: 'March 2',
      blood_type: 'S (RH-)',
      origin: 'North Blue',
      first_appearance: 'Chapter 43',
      first_arc: 'Baratie',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Cook'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: ['Observation', 'Armament'],
      description: 'Cook of the Straw Hat Pirates and Black Leg style martial artist.',
      image_url: 'https://cdn.myanimelist.net/images/characters/5/136769.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'chopper',
      name: 'Tony Tony Chopper',
      japanese_name: 'トニートニー・チョッパー',
      romanized_name: 'Tonī Tonī Choppā',
      aliases: ['Chopper', 'Cotton Candy Lover'],
      gender: 'Male',
      race: 'Other',
      status: 'Alive',
      age: 17,
      height: 90,
      bounty: 1000,
      birthday: 'December 24',
      blood_type: 'X',
      origin: 'Grand Line',
      first_appearance: 'Chapter 134',
      first_arc: 'Drum Island',
      devil_fruit_name: 'Hito Hito no Mi',
      devil_fruit_type: 'Zoan',
      occupations: ['Pirate', 'Doctor'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: [],
      description: 'Reindeer doctor of the Straw Hat Pirates who ate the Human-Human Fruit.',
      image_url: 'https://cdn.myanimelist.net/images/characters/3/263301.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'robin',
      name: 'Nico Robin',
      japanese_name: 'ニコ・ロビン',
      romanized_name: 'Niko Robin',
      aliases: ['Robin', 'Devil Child', 'Light of the Revolution'],
      gender: 'Female',
      race: 'Human',
      status: 'Alive',
      age: 30,
      height: 188,
      bounty: 930000000,
      birthday: 'February 6',
      blood_type: 'S',
      origin: 'West Blue',
      first_appearance: 'Chapter 114',
      first_arc: 'Whiskey Peak',
      devil_fruit_name: 'Hana Hana no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Archaeologist'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: ['Armament'],
      description: 'Archaeologist of the Straw Hat Pirates and sole survivor of Ohara.',
      image_url: 'https://cdn.myanimelist.net/images/characters/16/323386.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'franky',
      name: 'Franky',
      japanese_name: 'フランキー',
      romanized_name: 'Furankī',
      aliases: ['Cutty Flam', 'Iron Man Franky', 'Cyborg Franky'],
      gender: 'Male',
      race: 'Cyborg',
      status: 'Alive',
      age: 36,
      height: 240,
      bounty: 394000000,
      birthday: 'March 9',
      blood_type: 'XF',
      origin: 'South Blue',
      first_appearance: 'Chapter 329',
      first_arc: 'Water 7',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Shipwright'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: [],
      description: 'Cyborg shipwright who built the Thousand Sunny.',
      image_url: 'https://cdn.myanimelist.net/images/characters/11/136767.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'brook',
      name: 'Brook',
      japanese_name: 'ブルック',
      romanized_name: 'Burukku',
      aliases: ['Soul King', 'Humming Brook'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 90,
      height: 277,
      bounty: 383000000,
      birthday: 'April 3',
      blood_type: 'X',
      origin: 'West Blue',
      first_appearance: 'Chapter 442',
      first_arc: 'Florian Triangle',
      devil_fruit_name: 'Yomi Yomi no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Musician'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: [],
      description: 'Skeleton musician of the Straw Hats resurrected by the Revive-Revive Fruit.',
      image_url: 'https://cdn.myanimelist.net/images/characters/14/100787.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'jinbe',
      name: 'Jinbe',
      japanese_name: 'ジンベエ',
      romanized_name: 'Jinbē',
      aliases: ['First Knight of the Sea', 'Boss Jinbe'],
      gender: 'Male',
      race: 'Fish-Man',
      status: 'Alive',
      age: 46,
      height: 301,
      bounty: 1100000000,
      birthday: 'April 2',
      blood_type: 'F',
      origin: 'Grand Line',
      first_appearance: 'Chapter 528',
      first_arc: 'Impel Down',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Helmsman'],
      affiliations: ['Straw Hat Pirates'],
      haki_types: ['Observation', 'Armament'],
      description: 'Whale shark Fish-Man master of Fish-Man Karate and Helmsman of the Straw Hats.',
      image_url: 'https://cdn.myanimelist.net/images/characters/7/136765.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'shanks',
      name: 'Shanks',
      japanese_name: 'シャンクス',
      romanized_name: 'Shankusu',
      aliases: ['Red-Haired Shanks', 'Red Hair'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 39,
      height: 199,
      bounty: 4048900000,
      birthday: 'March 9',
      blood_type: 'XF',
      origin: 'West Blue',
      first_appearance: 'Chapter 1',
      first_arc: 'Romance Dawn',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Red Hair Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'One of the Four Emperors and the pirate who inspired Luffy.',
      image_url: 'https://cdn.myanimelist.net/images/characters/12/310309.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'buggy',
      name: 'Buggy',
      japanese_name: 'バギー',
      romanized_name: 'Bagī',
      aliases: ['Buggy the Clown', 'Star Clown'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 39,
      height: 198,
      bounty: 3189000000,
      birthday: 'August 8',
      blood_type: 'F',
      origin: 'Grand Line',
      first_appearance: 'Chapter 9',
      first_arc: 'Orange Town',
      devil_fruit_name: 'Bara Bara no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Cross Guild'],
      haki_types: [],
      description: 'Leader of Cross Guild and improbable Four Emperor.',
      image_url: 'https://cdn.myanimelist.net/images/characters/9/75533.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'mihawk',
      name: 'Dracule Mihawk',
      japanese_name: 'ジュラキュール・ミホーク',
      romanized_name: 'Jurakyūru Mihōku',
      aliases: ['Mihawk', 'Hawk-Eyes', 'World Strongest Swordsman'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 43,
      height: 198,
      bounty: 3590000000,
      birthday: 'March 9',
      blood_type: 'S',
      origin: 'West Blue',
      first_appearance: 'Chapter 49',
      first_arc: 'Baratie',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Swordsman'],
      affiliations: ['Cross Guild'],
      haki_types: ['Observation', 'Armament'],
      description: 'The World Strongest Swordsman and co-founder of Cross Guild.',
      image_url: 'https://cdn.myanimelist.net/images/characters/16/205623.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'crocodile',
      name: 'Sir Crocodile',
      japanese_name: 'クロコダイル',
      romanized_name: 'Kurokodairu',
      aliases: ['Crocodile', 'Desert King', 'Mr. 0'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 46,
      height: 253,
      bounty: 1965000000,
      birthday: 'September 5',
      blood_type: 'S',
      origin: 'Grand Line',
      first_appearance: 'Chapter 126',
      first_arc: 'Little Garden',
      devil_fruit_name: 'Suna Suna no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Pirate', 'Leader'],
      affiliations: ['Cross Guild'],
      haki_types: ['Observation', 'Armament'],
      description: 'Sand-manipulating former Warlord and mastermind behind Cross Guild.',
      image_url: 'https://cdn.myanimelist.net/images/characters/4/104928.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'law',
      name: 'Trafalgar D. Water Law',
      japanese_name: 'トラファルガー・D・ワーテル・ロー',
      romanized_name: 'Torafarugā Dī Wāteru Rō',
      aliases: ['Trafalgar Law', 'Law', 'Surgeon of Death'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 26,
      height: 191,
      bounty: 3000000000,
      birthday: 'October 6',
      blood_type: 'F',
      origin: 'North Blue',
      first_appearance: 'Chapter 498',
      first_arc: 'Sabaody Archipelago',
      devil_fruit_name: 'Ope Ope no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Captain', 'Doctor'],
      affiliations: ['Heart Pirates'],
      haki_types: ['Observation', 'Armament'],
      description: 'Captain of Heart Pirates and user of the Op-Op Fruit.',
      image_url: 'https://cdn.myanimelist.net/images/characters/4/204859.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'kid',
      name: 'Eustass Kid',
      japanese_name: 'ユースタス・キッド',
      romanized_name: 'Yūsutasu Kiddos',
      aliases: ['Captain Kid', 'Kid'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 23,
      height: 205,
      bounty: 3000000000,
      birthday: 'January 10',
      blood_type: 'F',
      origin: 'South Blue',
      first_appearance: 'Chapter 498',
      first_arc: 'Sabaody Archipelago',
      devil_fruit_name: 'Jiki Jiki no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Kid Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Magnetism-controlling captain of the Kid Pirates.',
      image_url: 'https://cdn.myanimelist.net/images/characters/16/205629.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'teach',
      name: 'Marshall D. Teach',
      japanese_name: 'マーシャル・D・ティーチ',
      romanized_name: 'Māsharu Dī Tīchi',
      aliases: ['Blackbeard', 'Teach'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 40,
      height: 344,
      bounty: 3996000000,
      birthday: 'August 3',
      blood_type: 'F',
      origin: 'Grand Line',
      first_appearance: 'Chapter 223',
      first_arc: 'Jaya',
      devil_fruit_name: 'Yami Yami no Mi & Gura Gura no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Pirate', 'Admiral'],
      affiliations: ['Blackbeard Pirates'],
      haki_types: ['Observation', 'Armament'],
      description: 'Only known person to wield two Devil Fruits simultaneously.',
      image_url: 'https://cdn.myanimelist.net/images/characters/5/104930.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'whitebeard',
      name: 'Edward Newgate',
      japanese_name: 'エドワード・ニューゲート',
      romanized_name: 'Edowādo Nyūgēto',
      aliases: ['Whitebeard', 'World Strongest Man'],
      gender: 'Male',
      race: 'Human',
      status: 'Dead',
      age: 72,
      height: 666,
      bounty: 5046000000,
      birthday: 'April 6',
      blood_type: 'F',
      origin: 'Grand Line',
      first_appearance: 'Chapter 234',
      first_arc: 'Jaya',
      devil_fruit_name: 'Gura Gura no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Whitebeard Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Legendary captain of the Whitebeard Pirates and rival to Roger.',
      image_url: 'https://cdn.myanimelist.net/images/characters/16/81577.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'roger',
      name: 'Gol D. Roger',
      japanese_name: 'ゴール・D・ロジャー',
      romanized_name: 'Gōru Dī Rojā',
      aliases: ['Gold Roger', 'Pirate King'],
      gender: 'Male',
      race: 'Human',
      status: 'Dead',
      age: 53,
      height: 274,
      bounty: 5564800000,
      birthday: 'December 31',
      blood_type: 'S',
      origin: 'East Blue',
      first_appearance: 'Chapter 1',
      first_arc: 'Romance Dawn',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Roger Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'The legendary Pirate King who conquered the Grand Line.',
      image_url: 'https://cdn.myanimelist.net/images/characters/7/81578.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'ace',
      name: 'Portgas D. Ace',
      japanese_name: 'ポートガス・D・エース',
      romanized_name: 'Pōtogasu Dī Ēsu',
      aliases: ['Fire Fist Ace', 'Gol D. Ace', 'Ace'],
      gender: 'Male',
      race: 'Human',
      status: 'Dead',
      age: 20,
      height: 185,
      bounty: 550000000,
      birthday: 'January 1',
      blood_type: 'S',
      origin: 'South Blue',
      first_appearance: 'Chapter 154',
      first_arc: 'Drum Island',
      devil_fruit_name: 'Mera Mera no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Pirate', 'Division Commander'],
      affiliations: ['Whitebeard Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Sworn brother of Luffy and 2nd Division Commander of Whitebeard Pirates.',
      image_url: 'https://cdn.myanimelist.net/images/characters/8/104926.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'sabo',
      name: 'Sabo',
      japanese_name: 'サボ',
      romanized_name: 'Sabo',
      aliases: ['Flame Emperor', 'Chief of Staff Sabo'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 22,
      height: 187,
      bounty: 602000000,
      birthday: 'March 20',
      blood_type: 'X',
      origin: 'East Blue',
      first_appearance: 'Chapter 583',
      first_arc: 'Post-War',
      devil_fruit_name: 'Mera Mera no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Revolutionary', 'Chief of Staff'],
      affiliations: ['Revolutionary Army'],
      haki_types: ['Observation', 'Armament'],
      description: 'Chief of Staff of the Revolutionary Army and sworn brother of Luffy.',
      image_url: 'https://cdn.myanimelist.net/images/characters/9/281691.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'dragon',
      name: 'Monkey D. Dragon',
      japanese_name: 'モンキー・D・ドラゴン',
      romanized_name: 'Monkī Dī Doragon',
      aliases: ['Dragon the Revolutionary', 'World Most Wanted Criminal'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 55,
      height: 256,
      bounty: 5000000000,
      birthday: 'October 5',
      blood_type: 'F',
      origin: 'East Blue',
      first_appearance: 'Chapter 100',
      first_arc: 'Loguetown',
      devil_fruit_name: 'Unknown',
      devil_fruit_type: 'Unknown',
      occupations: ['Revolutionary', 'Supreme Commander'],
      affiliations: ['Revolutionary Army'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Father of Luffy and Supreme Commander of the Revolutionary Army.',
      image_url: 'https://cdn.myanimelist.net/images/characters/6/81576.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'garp',
      name: 'Monkey D. Garp',
      japanese_name: 'モンキー・D・ガープ',
      romanized_name: 'Monkī Dī Gāpu',
      aliases: ['Garp the Fist', 'Hero of the Marines'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 78,
      height: 287,
      bounty: 3000000000,
      birthday: 'May 2',
      blood_type: 'F',
      origin: 'East Blue',
      first_appearance: 'Chapter 92',
      first_arc: 'Arlong Park',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Marine', 'Vice Admiral'],
      affiliations: ['Marines'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Legendary Marine Hero and grandfather of Luffy.',
      image_url: 'https://cdn.myanimelist.net/images/characters/3/81575.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'akainu',
      name: 'Sakazuki',
      japanese_name: 'サカズキ',
      romanized_name: 'Sakazuki',
      aliases: ['Akainu', 'Fleet Admiral Sakazuki'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 55,
      height: 306,
      bounty: 5000000000,
      birthday: 'August 16',
      blood_type: 'F',
      origin: 'North Blue',
      first_appearance: 'Chapter 397',
      first_arc: 'Enies Lobby',
      devil_fruit_name: 'Magu Magu no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Marine', 'Fleet Admiral'],
      affiliations: ['Marines'],
      haki_types: ['Observation', 'Armament'],
      description: 'Fleet Admiral of the Marines believing in Absolute Justice.',
      image_url: 'https://cdn.myanimelist.net/images/characters/14/104932.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'kizaru',
      name: 'Borsalino',
      japanese_name: 'ボルサリーノ',
      romanized_name: 'Borusarīno',
      aliases: ['Kizaru', 'Yellow Monkey'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 58,
      height: 302,
      bounty: 3000000000,
      birthday: 'November 23',
      blood_type: 'XF',
      origin: 'North Blue',
      first_appearance: 'Chapter 504',
      first_arc: 'Sabaody Archipelago',
      devil_fruit_name: 'Pika Pika no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Marine', 'Admiral'],
      affiliations: ['Marines'],
      haki_types: ['Observation', 'Armament'],
      description: 'Marine Admiral possessing the speed of light.',
      image_url: 'https://cdn.myanimelist.net/images/characters/16/104934.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'kuzan',
      name: 'Kuzan',
      japanese_name: 'クザン',
      romanized_name: 'Kuzan',
      aliases: ['Aokiji', 'Blue Pheasant'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 49,
      height: 298,
      bounty: 3000000000,
      birthday: 'September 21',
      blood_type: 'F',
      origin: 'South Blue',
      first_appearance: 'Chapter 319',
      first_arc: 'Long Ring Long Land',
      devil_fruit_name: 'Hie Hie no Mi',
      devil_fruit_type: 'Logia',
      occupations: ['Pirate', 'Titanic Captain'],
      affiliations: ['Blackbeard Pirates'],
      haki_types: ['Observation', 'Armament'],
      description: 'Former Marine Admiral who joined the Blackbeard Pirates.',
      image_url: 'https://cdn.myanimelist.net/images/characters/4/104936.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'fujitora',
      name: 'Issho',
      japanese_name: 'イッショウ',
      romanized_name: 'Isshō',
      aliases: ['Fujitora', 'Wisteria Tiger'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 54,
      height: 270,
      bounty: 3000000000,
      birthday: 'August 10',
      blood_type: 'S',
      origin: 'Grand Line',
      first_appearance: 'Chapter 701',
      first_arc: 'Dressrosa',
      devil_fruit_name: 'Zushi Zushi no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Marine', 'Admiral'],
      affiliations: ['Marines'],
      haki_types: ['Observation', 'Armament'],
      description: 'Blind Marine Admiral manipulating gravity.',
      image_url: 'https://cdn.myanimelist.net/images/characters/11/244349.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'doflamingo',
      name: 'Donquixote Doflamingo',
      japanese_name: 'ドンキホーテ・ドフラミンゴ',
      romanized_name: 'Donkihōte Dofuramingo',
      aliases: ['Doflamingo', 'Heavenly Yaksha', 'Joker'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 41,
      height: 305,
      bounty: 340000000,
      birthday: 'October 23',
      blood_type: 'X',
      origin: 'North Blue',
      first_appearance: 'Chapter 234',
      first_arc: 'Jaya',
      devil_fruit_name: 'Ito Ito no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Donquixote Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Former Warlord and ruler of Dressrosa using Awakened String Fruit.',
      image_url: 'https://cdn.myanimelist.net/images/characters/9/194451.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'katakuri',
      name: 'Charlotte Katakuri',
      japanese_name: 'シャーロット・カタクリ',
      romanized_name: 'Shārotto Katakuri',
      aliases: ['Katakuri', 'Sweet Commander Katakuri'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 48,
      height: 509,
      bounty: 1057000000,
      birthday: 'November 25',
      blood_type: 'XF',
      origin: 'Grand Line',
      first_appearance: 'Chapter 860',
      first_arc: 'Whole Cake Island',
      devil_fruit_name: 'Mochi Mochi no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Sweet Commander'],
      affiliations: ['Big Mom Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Strongest Sweet Commander with Future Sight Observation Haki.',
      image_url: 'https://cdn.myanimelist.net/images/characters/13/354422.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'bigmom',
      name: 'Charlotte Linlin',
      japanese_name: 'シャーロット・リンリン',
      romanized_name: 'Shārotto Rinrin',
      aliases: ['Big Mom', 'Linlin'],
      gender: 'Female',
      race: 'Human',
      status: 'Unknown',
      age: 68,
      height: 880,
      bounty: 4388000000,
      birthday: 'February 15',
      blood_type: 'X',
      origin: 'Grand Line',
      first_appearance: 'Chapter 651',
      first_arc: 'Fish-Man Island',
      devil_fruit_name: 'Soru Soru no Mi',
      devil_fruit_type: 'Paramecia',
      occupations: ['Pirate', 'Captain'],
      affiliations: ['Big Mom Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Matriarch of Totto Land possessing soul-manipulating powers.',
      image_url: 'https://cdn.myanimelist.net/images/characters/6/323388.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'kaidou',
      name: 'Kaidou',
      japanese_name: 'カイドウ',
      romanized_name: 'Kaidō',
      aliases: ['Kaidou of the Beasts', 'Strongest Creature'],
      gender: 'Male',
      race: 'Other',
      status: 'Unknown',
      age: 59,
      height: 710,
      bounty: 4611100000,
      birthday: 'May 1',
      blood_type: 'F',
      origin: 'Grand Line',
      first_appearance: 'Chapter 795',
      first_arc: 'Dressrosa',
      devil_fruit_name: 'Uo Uo no Mi, Model: Seiryu',
      devil_fruit_type: 'Mythical Zoan',
      devil_fruit_model: 'Seiryu',
      occupations: ['Pirate', 'Governor-General'],
      affiliations: ['Beast Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Governor-General of the Beast Pirates and the Azure Dragon of Wano.',
      image_url: 'https://cdn.myanimelist.net/images/characters/7/310311.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'yamato',
      name: 'Yamato',
      japanese_name: 'ヤマト',
      romanized_name: 'Yamato',
      aliases: ['Kouzuki Oden', 'Oni Princess'],
      gender: 'Female',
      race: 'Other',
      status: 'Alive',
      age: 28,
      height: 263,
      bounty: 0,
      birthday: 'November 3',
      blood_type: 'F',
      origin: 'Grand Line',
      first_appearance: 'Chapter 971',
      first_arc: 'Wano Country',
      devil_fruit_name: 'Inu Inu no Mi, Model: Okuchi no Makami',
      devil_fruit_type: 'Mythical Zoan',
      devil_fruit_model: 'Okuchi no Makami',
      occupations: ['Guardian', 'Warrior'],
      affiliations: ['Wano Country'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'Child of Kaidou who inherits Oden will to protect Wano.',
      image_url: 'https://cdn.myanimelist.net/images/characters/11/438692.jpg',
    },
    {
      source_id: 'wikidataset',
      source_character_id: 'rayleigh',
      name: 'Silvers Rayleigh',
      japanese_name: 'シルバーズ・レイリー',
      romanized_name: 'Shirubāzu Reirī',
      aliases: ['Dark King', 'Right Hand of the Pirate King'],
      gender: 'Male',
      race: 'Human',
      status: 'Alive',
      age: 78,
      height: 188,
      bounty: 0,
      birthday: 'May 13',
      blood_type: 'XF',
      origin: 'Grand Line',
      first_appearance: 'Chapter 500',
      first_arc: 'Sabaody Archipelago',
      devil_fruit_name: 'None',
      devil_fruit_type: 'None',
      occupations: ['Coating Mechanic', 'First Mate'],
      affiliations: ['Roger Pirates'],
      haki_types: ['Observation', 'Armament', 'Conqueror'],
      description: 'First Mate of the Roger Pirates and mentor to Luffy in Haki.',
      image_url: 'https://cdn.myanimelist.net/images/characters/15/81574.jpg',
    },
  ];
}
