import { createAdminClient } from '../lib/supabase/admin';

interface CharacterFact {
  name: string;
  aliases?: string[];
  japanese_name?: string;
  romanized_name?: string;
  gender: string;
  race: string;
  status: string;
  age: number | null;
  height: number | null;
  bounty: number | null;
  origin: string;
  first_appearance: string;
  first_arc: string;
  devil_fruit_name?: string | null;
  devil_fruit_type?: string;
  devil_fruit_model?: string | null;
  haki?: string[];
  affiliations?: string[];
  occupations?: string[];
  image_url?: string;
}

const FAMOUS_CHARACTERS: CharacterFact[] = [
  // Straw Hats
  {
    name: 'Monkey D. Luffy',
    aliases: ['Straw Hat Luffy', 'Mugiwara', 'Joy Boy', 'Fifth Emperor', 'Sun God'],
    japanese_name: 'モンキー・D・ルフィ',
    romanized_name: 'Monkī D. Rufi',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 19,
    height: 174,
    bounty: 3000000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 1',
    first_arc: 'Romance Dawn',
    devil_fruit_name: 'Hito Hito no Mi, Model: Nika',
    devil_fruit_type: 'Mythical Zoan',
    devil_fruit_model: 'Nika',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Straw Hat Pirates', 'Straw Hat Grand Fleet'],
    occupations: ['Captain', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/9/310307.jpg',
  },
  {
    name: 'Roronoa Zoro',
    aliases: ['Pirate Hunter', 'King of Hell', 'Marimo'],
    japanese_name: 'ロロノア・ゾロ',
    romanized_name: 'Roronoa Zoro',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 21,
    height: 181,
    bounty: 1111000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 3',
    first_arc: 'Romance Dawn',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Straw Hat Pirates'],
    occupations: ['Swordsman', 'Combatant', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/3/100534.jpg',
  },
  {
    name: 'Nami',
    aliases: ['Cat Burglar', 'Weather Fairy'],
    japanese_name: 'ナミ',
    romanized_name: 'Nami',
    gender: 'Female',
    race: 'Human',
    status: 'Alive',
    age: 20,
    height: 170,
    bounty: 366000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 8',
    first_arc: 'Orange Town',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: [],
    affiliations: ['Straw Hat Pirates'],
    occupations: ['Navigator', 'Pirate', 'Thief'],
    image_url: 'https://cdn.myanimelist.net/images/characters/2/263249.jpg',
  },
  {
    name: 'Usopp',
    aliases: ['God Usopp', 'Sogeking', 'Sniper King'],
    japanese_name: 'ウソップ',
    romanized_name: 'Usoppu',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 19,
    height: 176,
    bounty: 500000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 23',
    first_arc: 'Syrup Village',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation'],
    affiliations: ['Straw Hat Pirates'],
    occupations: ['Sniper', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/5/283995.jpg',
  },
  {
    name: 'Sanji',
    aliases: ['Black Leg Sanji', 'Stealth Black', 'O-Soba Mask', 'Vinsmoke Sanji'],
    japanese_name: 'サンジ',
    romanized_name: 'Sanji',
    gender: 'Male',
    race: 'Human (Genetically Enhanced)',
    status: 'Alive',
    age: 21,
    height: 180,
    bounty: 1032000000,
    origin: 'North Blue',
    first_appearance: 'Chapter 43',
    first_arc: 'Baratie',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament'],
    affiliations: ['Straw Hat Pirates', 'Germa Kingdom (Former)', 'Baratie (Former)'],
    occupations: ['Cook', 'Pirate', 'Martial Artist'],
    image_url: 'https://cdn.myanimelist.net/images/characters/5/136769.jpg',
  },
  {
    name: 'Tony Tony Chopper',
    aliases: ['Cotton Candy Lover Chopper', 'Emergency Food'],
    japanese_name: 'トニートニー・チョッパー',
    romanized_name: 'Tonī Tonī Choppā',
    gender: 'Male',
    race: 'Animal (Reindeer)',
    status: 'Alive',
    age: 17,
    height: 90,
    bounty: 1000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 134',
    first_arc: 'Drum Island',
    devil_fruit_name: 'Hito Hito no Mi',
    devil_fruit_type: 'Zoan',
    haki: [],
    affiliations: ['Straw Hat Pirates'],
    occupations: ['Doctor', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/3/267323.jpg',
  },
  {
    name: 'Nico Robin',
    aliases: ['Devil Child', 'Light of the Revolution', 'Miss All Sunday'],
    japanese_name: 'ニコ・ロビン',
    romanized_name: 'Niko Robin',
    gender: 'Female',
    race: 'Human',
    status: 'Alive',
    age: 30,
    height: 188,
    bounty: 930000000,
    origin: 'West Blue',
    first_appearance: 'Chapter 114',
    first_arc: 'Whiskey Peak',
    devil_fruit_name: 'Hana Hana no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Armament'],
    affiliations: ['Straw Hat Pirates', 'Baroque Works (Former)', 'Revolutionary Army (Associate)'],
    occupations: ['Archaeologist', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/11/498263.jpg',
  },
  {
    name: 'Franky',
    aliases: ['Cyborg Franky', 'Iron Man', 'Cutty Flam'],
    japanese_name: 'フランキー',
    romanized_name: 'Furankī',
    gender: 'Male',
    race: 'Cyborg',
    status: 'Alive',
    age: 36,
    height: 240,
    bounty: 394000000,
    origin: 'South Blue',
    first_appearance: 'Chapter 329',
    first_arc: 'Water 7',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: [],
    affiliations: ['Straw Hat Pirates', 'Franky Family (Former)', 'Tom\'s Workers (Former)'],
    occupations: ['Shipwright', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/14/461247.jpg',
  },
  {
    name: 'Brook',
    aliases: ['Soul King', 'Humming Brook', 'Dead Bones'],
    japanese_name: 'ブルック',
    romanized_name: 'Burukku',
    gender: 'Male',
    race: 'Human (Undead)',
    status: 'Alive',
    age: 90,
    height: 277,
    bounty: 383000000,
    origin: 'West Blue',
    first_appearance: 'Chapter 442',
    first_arc: 'Thriller Bark',
    devil_fruit_name: 'Yomi Yomi no Mi',
    devil_fruit_type: 'Paramecia',
    haki: [],
    affiliations: ['Straw Hat Pirates', 'Rumbar Pirates (Former)'],
    occupations: ['Musician', 'Swordsman', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/11/42790.jpg',
  },
  {
    name: 'Jinbe',
    aliases: ['Knight of the Sea', 'First Son of the Sea'],
    japanese_name: 'ジンベエ',
    romanized_name: 'Jinbē',
    gender: 'Male',
    race: 'Fish-Man',
    status: 'Alive',
    age: 46,
    height: 301,
    bounty: 1100000000,
    origin: 'Fish-Man Island',
    first_appearance: 'Chapter 528',
    first_arc: 'Impel Down',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament'],
    affiliations: ['Straw Hat Pirates', 'Sun Pirates (Former)', 'Seven Warlords of the Sea (Former)', 'Big Mom Pirates (Former)'],
    occupations: ['Helmsman', 'Pirate', 'Fish-Man Karate Master'],
    image_url: 'https://cdn.myanimelist.net/images/characters/11/98555.jpg',
  },

  // Emperors & Top Tier Legends
  {
    name: 'Shanks',
    aliases: ['Red-Haired Shanks', 'Red Hair', 'Akagami'],
    japanese_name: 'シャンクス',
    romanized_name: 'Shankusu',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 39,
    height: 199,
    bounty: 4048900000,
    origin: 'West Blue',
    first_appearance: 'Chapter 1',
    first_arc: 'Romance Dawn',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Red Hair Pirates', 'Roger Pirates (Former)', 'Four Emperors'],
    occupations: ['Chief', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/12/309440.jpg',
  },
  {
    name: 'Marshall D. Teach',
    aliases: ['Blackbeard', 'Kurohige'],
    japanese_name: 'マーシャル・D・ティーチ',
    romanized_name: 'Māsharu D. Tīchi',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 40,
    height: 344,
    bounty: 3996000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 223',
    first_arc: 'Jaya',
    devil_fruit_name: 'Yami Yami no Mi & Gura Gura no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Blackbeard Pirates', 'Whitebeard Pirates (Former)', 'Seven Warlords of the Sea (Former)', 'Four Emperors'],
    occupations: ['Admiral', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/327317.jpg',
  },
  {
    name: 'Edward Newgate',
    aliases: ['Whitebeard', 'Shirohige', 'Strongest Man in the World'],
    japanese_name: 'エドワード・ニューゲート',
    romanized_name: 'Edowādo Nyūgēto',
    gender: 'Male',
    race: 'Human',
    status: 'Deceased',
    age: 72,
    height: 666,
    bounty: 5046000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 234',
    first_arc: 'Jaya',
    devil_fruit_name: 'Gura Gura no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Whitebeard Pirates', 'Rocks Pirates (Former)', 'Four Emperors'],
    occupations: ['Captain', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/74833.jpg',
  },
  {
    name: 'Kaido',
    aliases: ['King of the Beasts', 'Strongest Creature in the World', 'Kaido of the Beasts'],
    japanese_name: 'カイドウ',
    romanized_name: 'Kaidō',
    gender: 'Male',
    race: 'Oni',
    status: 'Unknown',
    age: 59,
    height: 710,
    bounty: 4611100000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 795',
    first_arc: 'Dressrosa',
    devil_fruit_name: 'Uo Uo no Mi, Model: Seiryu',
    devil_fruit_type: 'Mythical Zoan',
    devil_fruit_model: 'Seiryu',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Beasts Pirates', 'Rocks Pirates (Former)', 'Four Emperors'],
    occupations: ['Governor-General', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/12/393275.jpg',
  },
  {
    name: 'Charlotte Linlin',
    aliases: ['Big Mom'],
    japanese_name: 'シャーロット・リンリン',
    romanized_name: 'Shārotto Rinrin',
    gender: 'Female',
    race: 'Human',
    status: 'Unknown',
    age: 68,
    height: 880,
    bounty: 4388000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 651',
    first_arc: 'Fish-Man Island',
    devil_fruit_name: 'Soru Soru no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Big Mom Pirates', 'Rocks Pirates (Former)', 'Four Emperors', 'Totto Land'],
    occupations: ['Captain', 'Queen', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/12/327318.jpg',
  },
  {
    name: 'Gol D. Roger',
    aliases: ['Pirate King', 'Gold Roger'],
    japanese_name: 'ゴール・D・ロジャー',
    romanized_name: 'Gōru D. Rojā',
    gender: 'Male',
    race: 'Human',
    status: 'Deceased',
    age: 53,
    height: 274,
    bounty: 5564800000,
    origin: 'East Blue',
    first_appearance: 'Chapter 1',
    first_arc: 'Romance Dawn',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Roger Pirates'],
    occupations: ['Pirate King', 'Captain', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/81308.jpg',
  },
  {
    name: 'Silvers Rayleigh',
    aliases: ['Dark King', 'Right Hand of the Pirate King'],
    japanese_name: 'シルバーズ・レイリー',
    romanized_name: 'Shirubāzu Reirī',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 78,
    height: 188,
    bounty: null,
    origin: 'Grand Line',
    first_appearance: 'Chapter 500',
    first_arc: 'Sabaody Archipelago',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Roger Pirates (Former)'],
    occupations: ['First Mate', 'Coating Mechanic', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/14/79435.jpg',
  },

  // Warlords & Supernovas
  {
    name: 'Dracule Mihawk',
    aliases: ['Hawk Eyes', 'Strongest Swordsman in the World'],
    japanese_name: 'ジュラキュール・ミホーク',
    romanized_name: 'Jurakyūru Mihōku',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 43,
    height: 198,
    bounty: 3590000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 49',
    first_arc: 'Baratie',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament'],
    affiliations: ['Cross Guild', 'Seven Warlords of the Sea (Former)'],
    occupations: ['Swordsman', 'Pirate', 'Officer'],
    image_url: 'https://cdn.myanimelist.net/images/characters/15/284149.jpg',
  },
  {
    name: 'Crocodile',
    aliases: ['Sir Crocodile', 'Desert King', 'Mr. 0'],
    japanese_name: 'クロコダイル',
    romanized_name: 'Kurokodairu',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 46,
    height: 253,
    bounty: 1965000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 126',
    first_arc: 'Little Garden',
    devil_fruit_name: 'Suna Suna no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Cross Guild', 'Baroque Works (Former)', 'Seven Warlords of the Sea (Former)'],
    occupations: ['President', 'Pirate', 'Officer'],
    image_url: 'https://cdn.myanimelist.net/images/characters/12/32338.jpg',
  },
  {
    name: 'Boa Hancock',
    aliases: ['Pirate Empress', 'Snake Princess'],
    japanese_name: 'ボア・ハンコック',
    romanized_name: 'Boa Hankokku',
    gender: 'Female',
    race: 'Human',
    status: 'Alive',
    age: 31,
    height: 191,
    bounty: 1659000000,
    origin: 'Calm Belt',
    first_appearance: 'Chapter 516',
    first_arc: 'Amazon Lily',
    devil_fruit_name: 'Mero Mero no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Kuja Pirates', 'Amazon Lily', 'Seven Warlords of the Sea (Former)'],
    occupations: ['Empress', 'Captain', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/14/87391.jpg',
  },
  {
    name: 'Donquixote Doflamingo',
    aliases: ['Heavenly Yaksha', 'Joker'],
    japanese_name: 'ドンキホーテ・ドフラミンゴ',
    romanized_name: 'Donkihōte Dofuramingo',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 41,
    height: 305,
    bounty: 340000000,
    origin: 'North Blue',
    first_appearance: 'Chapter 234',
    first_arc: 'Jaya',
    devil_fruit_name: 'Ito Ito no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Donquixote Pirates', 'Dressrosa (Former)', 'Seven Warlords of the Sea (Former)', 'World Nobles (Former)'],
    occupations: ['Captain', 'King', 'Underworld Broker', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/10/246473.jpg',
  },
  {
    name: 'Trafalgar D. Water Law',
    aliases: ['Surgeon of Death', 'Trafalgar Law'],
    japanese_name: 'トラファルガー・D・ワーテル・ロー',
    romanized_name: 'Torafarugā D. Wāteru Rō',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 26,
    height: 191,
    bounty: 3000000000,
    origin: 'North Blue',
    first_appearance: 'Chapter 498',
    first_arc: 'Sabaody Archipelago',
    devil_fruit_name: 'Ope Ope no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Heart Pirates', 'Ninja-Pirate-Mink-Samurai Alliance (Former)', 'Seven Warlords of the Sea (Former)'],
    occupations: ['Captain', 'Doctor', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/4/111999.jpg',
  },
  {
    name: 'Eustass Kid',
    aliases: ['Captain Kid'],
    japanese_name: 'ユースタス・キッド',
    romanized_name: 'Yūsutasu Kiddo',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 23,
    height: 205,
    bounty: 3000000000,
    origin: 'South Blue',
    first_appearance: 'Chapter 498',
    first_arc: 'Sabaody Archipelago',
    devil_fruit_name: 'Jiki Jiki no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Kid Pirates'],
    occupations: ['Captain', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/81309.jpg',
  },
  {
    name: 'Portgas D. Ace',
    aliases: ['Fire Fist Ace'],
    japanese_name: 'ポートガス・D・エース',
    romanized_name: 'Pōtogasu D. Ēsu',
    gender: 'Male',
    race: 'Human',
    status: 'Deceased',
    age: 20,
    height: 185,
    bounty: 550000000,
    origin: 'South Blue',
    first_appearance: 'Chapter 154',
    first_arc: 'Drum Island',
    devil_fruit_name: 'Mera Mera no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Whitebeard Pirates', 'Spade Pirates (Former)'],
    occupations: ['2nd Division Commander', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/6/81307.jpg',
  },
  {
    name: 'Sabo',
    aliases: ['Flame Emperor', 'Chief of Staff'],
    japanese_name: 'サボ',
    romanized_name: 'Sabo',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 22,
    height: 187,
    bounty: 602000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 583',
    first_arc: 'Post-War',
    devil_fruit_name: 'Mera Mera no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Revolutionary Army'],
    occupations: ['Chief of Staff', 'Revolutionary'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/327316.jpg',
  },
  {
    name: 'Monkey D. Dragon',
    aliases: ['World\'s Worst Criminal', 'The Rebel'],
    japanese_name: 'モンキー・D・ドラゴン',
    romanized_name: 'Monkī D. Doragon',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 55,
    height: 256,
    bounty: null,
    origin: 'East Blue',
    first_appearance: 'Chapter 100',
    first_arc: 'Loguetown',
    devil_fruit_name: null,
    devil_fruit_type: 'Unknown',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Revolutionary Army'],
    occupations: ['Supreme Commander', 'Revolutionary'],
    image_url: 'https://cdn.myanimelist.net/images/characters/11/327319.jpg',
  },
  {
    name: 'Monkey D. Garp',
    aliases: ['Hero of the Marines', 'Garp the Fist'],
    japanese_name: 'モンキー・D・ガープ',
    romanized_name: 'Monkī D. Gāpu',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 78,
    height: 287,
    bounty: 3000000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 92',
    first_arc: 'Arlong Park',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Marines'],
    occupations: ['Vice Admiral', 'Instructor', 'Marine'],
    image_url: 'https://cdn.myanimelist.net/images/characters/12/327320.jpg',
  },
  {
    name: 'Sakazuki',
    aliases: ['Akainu', 'Red Dog'],
    japanese_name: 'サカズキ',
    romanized_name: 'Sakazuki',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 55,
    height: 306,
    bounty: 5000000000,
    origin: 'North Blue',
    first_appearance: 'Chapter 397',
    first_arc: 'Enies Lobby',
    devil_fruit_name: 'Magu Magu no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Marines'],
    occupations: ['Fleet Admiral', 'Marine'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/161477.jpg',
  },
  {
    name: 'Kuzan',
    aliases: ['Aokiji', 'Blue Pheasant'],
    japanese_name: 'クザン',
    romanized_name: 'Kuzan',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 49,
    height: 298,
    bounty: null,
    origin: 'South Blue',
    first_appearance: 'Chapter 319',
    first_arc: 'Long Ring Long Land',
    devil_fruit_name: 'Hie Hie no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Blackbeard Pirates', 'Marines (Former)'],
    occupations: ['Titanic Captain', 'Admiral (Former)', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/10/81306.jpg',
  },
  {
    name: 'Borsalino',
    aliases: ['Kizaru', 'Yellow Monkey'],
    japanese_name: 'ボルサリーノ',
    romanized_name: 'Borusarīno',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 58,
    height: 302,
    bounty: 3000000000,
    origin: 'North Blue',
    first_appearance: 'Chapter 504',
    first_arc: 'Sabaody Archipelago',
    devil_fruit_name: 'Pika Pika no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Marines'],
    occupations: ['Admiral', 'Marine'],
    image_url: 'https://cdn.myanimelist.net/images/characters/14/81305.jpg',
  },
  {
    name: 'Buggy',
    aliases: ['Buggy the Clown', 'Star Clown', 'The Genius Jester'],
    japanese_name: 'バギー',
    romanized_name: 'Bagī',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 39,
    height: 192,
    bounty: 3189000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 9',
    first_arc: 'Orange Town',
    devil_fruit_name: 'Bara Bara no Mi',
    devil_fruit_type: 'Paramecia',
    haki: [],
    affiliations: ['Cross Guild', 'Buggy Pirates', 'Roger Pirates (Former)', 'Four Emperors'],
    occupations: ['Leader', 'Pirate', 'Emperor'],
    image_url: 'https://cdn.myanimelist.net/images/characters/6/51239.jpg',
  },
  {
    name: 'Koby',
    aliases: ['Hero of the Marines'],
    japanese_name: 'コビー',
    romanized_name: 'Kobī',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 18,
    height: 167,
    bounty: 500000000,
    origin: 'East Blue',
    first_appearance: 'Chapter 2',
    first_arc: 'Romance Dawn',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Marines', 'SWORD'],
    occupations: ['Captain', 'Marine'],
    image_url: 'https://cdn.myanimelist.net/images/characters/15/309441.jpg',
  },
  {
    name: 'Charlotte Katakuri',
    aliases: ['Sweet Commander Katakuri'],
    japanese_name: 'シャーロット・カタクリ',
    romanized_name: 'Shārotto Katakuri',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 48,
    height: 509,
    bounty: 1057000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 860',
    first_arc: 'Whole Cake Island',
    devil_fruit_name: 'Mochi Mochi no Mi',
    devil_fruit_type: 'Special Paramecia',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Big Mom Pirates', 'Totto Land'],
    occupations: ['Sweet Commander', 'Minister of Flour', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/15/347432.jpg',
  },
  {
    name: 'Yamato',
    aliases: ['Son of Kaido', 'Kozuki Oden', 'Demon Princess'],
    japanese_name: 'ヤマト',
    romanized_name: 'Yamato',
    gender: 'Female',
    race: 'Oni',
    status: 'Alive',
    age: 28,
    height: 263,
    bounty: null,
    origin: 'Grand Line',
    first_appearance: 'Chapter 983',
    first_arc: 'Wano Country',
    devil_fruit_name: 'Inu Inu no Mi, Model: Okuchi no Makami',
    devil_fruit_type: 'Mythical Zoan',
    devil_fruit_model: 'Okuchi no Makami',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Wano Country', 'Beasts Pirates (Former)'],
    occupations: ['Warrior', 'Guardian Deity of Wano'],
    image_url: 'https://cdn.myanimelist.net/images/characters/5/453298.jpg',
  },
  {
    name: 'Bartholomew Kuma',
    aliases: ['Tyrant', 'Pacifista Prototype'],
    japanese_name: 'バーソロミュー・くま',
    romanized_name: 'Bāsoromyū Kuma',
    gender: 'Male',
    race: 'Buccaneer',
    status: 'Alive',
    age: 47,
    height: 689,
    bounty: 296000000,
    origin: 'South Blue',
    first_appearance: 'Chapter 233',
    first_arc: 'Jaya',
    devil_fruit_name: 'Nikyu Nikyu no Mi',
    devil_fruit_type: 'Paramecia',
    haki: ['Observation', 'Armament'],
    affiliations: ['Revolutionary Army', 'Sorbet Kingdom (Former)', 'Seven Warlords of the Sea (Former)'],
    occupations: ['King (Former)', 'Officer', 'Revolutionary'],
    image_url: 'https://cdn.myanimelist.net/images/characters/5/52778.jpg',
  },
  {
    name: 'Rob Lucci',
    aliases: ['Massacre Weapon', 'Cipher Pol Aigis Zero'],
    japanese_name: 'ロブ・ルッチ',
    romanized_name: 'Robu Rutchi',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 30,
    height: 212,
    bounty: null,
    origin: 'Grand Line',
    first_appearance: 'Chapter 323',
    first_arc: 'Water 7',
    devil_fruit_name: 'Neko Neko no Mi, Model: Leopard',
    devil_fruit_type: 'Zoan',
    devil_fruit_model: 'Leopard',
    haki: ['Observation', 'Armament'],
    affiliations: ['CP0', 'CP9 (Former)', 'World Government'],
    occupations: ['Agent', 'Assassin', 'Chief Agent'],
    image_url: 'https://cdn.myanimelist.net/images/characters/6/87868.jpg',
  },
  {
    name: 'Enel',
    aliases: ['God Enel', 'God of Skypiea', 'Eneru'],
    japanese_name: 'エネル',
    romanized_name: 'Eneru',
    gender: 'Male',
    race: 'Birkan',
    status: 'Alive',
    age: 39,
    height: 266,
    bounty: null,
    origin: 'Sky Island',
    first_appearance: 'Chapter 254',
    first_arc: 'Skypiea',
    devil_fruit_name: 'Goro Goro no Mi',
    devil_fruit_type: 'Logia',
    haki: ['Observation'],
    affiliations: ['God\'s Army', 'Birka (Former)'],
    occupations: ['God of Skypiea (Former)', 'Ruler'],
    image_url: 'https://cdn.myanimelist.net/images/characters/16/81304.jpg',
  },
  {
    name: 'Kozuki Oden',
    aliases: ['Lord Oden', 'Fool of a Lord'],
    japanese_name: '光月おでん',
    romanized_name: 'Kōzuki Oden',
    gender: 'Male',
    race: 'Human',
    status: 'Deceased',
    age: 39,
    height: 382,
    bounty: 3500000000,
    origin: 'Wano Country',
    first_appearance: 'Chapter 818',
    first_arc: 'Zou',
    devil_fruit_name: null,
    devil_fruit_type: 'None',
    haki: ['Observation', 'Armament', 'Conqueror'],
    affiliations: ['Kozuki Clan', 'Whitebeard Pirates (Former)', 'Roger Pirates (Former)'],
    occupations: ['Daimyo of Kuri', 'Division Commander', 'Pirate', 'Samurai'],
    image_url: 'https://cdn.myanimelist.net/images/characters/8/429402.jpg',
  },
  {
    name: 'King',
    aliases: ['King the Wildfire', 'Arber', 'Alber'],
    japanese_name: 'キング',
    romanized_name: 'Kingu',
    gender: 'Male',
    race: 'Lunarian',
    status: 'Alive',
    age: 47,
    height: 613,
    bounty: 1390000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 925',
    first_arc: 'Wano Country',
    devil_fruit_name: 'Ryu Ryu no Mi, Model: Pteranodon',
    devil_fruit_type: 'Ancient Zoan',
    devil_fruit_model: 'Pteranodon',
    haki: ['Observation', 'Armament'],
    affiliations: ['Beasts Pirates'],
    occupations: ['Lead Performer', 'All-Star', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/13/453299.jpg',
  },
  {
    name: 'Queen',
    aliases: ['Queen the Plague'],
    japanese_name: 'クイーン',
    romanized_name: 'Kuīn',
    gender: 'Male',
    race: 'Cyborg',
    status: 'Alive',
    age: 56,
    height: 612,
    bounty: 1320000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 925',
    first_arc: 'Wano Country',
    devil_fruit_name: 'Ryu Ryu no Mi, Model: Brachiosaurus',
    devil_fruit_type: 'Ancient Zoan',
    devil_fruit_model: 'Brachiosaurus',
    haki: ['Observation', 'Armament'],
    affiliations: ['Beasts Pirates', 'MADS (Former)'],
    occupations: ['Lead Performer', 'All-Star', 'Scientist', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/12/453300.jpg',
  },
  {
    name: 'Jack',
    aliases: ['Jack the Drought'],
    japanese_name: 'ジャック',
    romanized_name: 'Jakku',
    gender: 'Male',
    race: 'Fish-Man',
    status: 'Alive',
    age: 28,
    height: 830,
    bounty: 1000000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 801',
    first_arc: 'Zou',
    devil_fruit_name: 'Zou Zou no Mi, Model: Mammoth',
    devil_fruit_type: 'Ancient Zoan',
    devil_fruit_model: 'Mammoth',
    haki: ['Observation', 'Armament'],
    affiliations: ['Beasts Pirates'],
    occupations: ['Lead Performer', 'All-Star', 'Captain', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/6/309442.jpg',
  },
  {
    name: 'Marco',
    aliases: ['Marco the Phoenix', 'Pineapple Head'],
    japanese_name: 'マルコ',
    romanized_name: 'Maruko',
    gender: 'Male',
    race: 'Human',
    status: 'Alive',
    age: 45,
    height: 203,
    bounty: 1374000000,
    origin: 'Grand Line',
    first_appearance: 'Chapter 234',
    first_arc: 'Jaya',
    devil_fruit_name: 'Tori Tori no Mi, Model: Phoenix',
    devil_fruit_type: 'Mythical Zoan',
    devil_fruit_model: 'Phoenix',
    haki: ['Observation', 'Armament'],
    affiliations: ['Whitebeard Pirates'],
    occupations: ['1st Division Commander', 'Doctor', 'Pirate'],
    image_url: 'https://cdn.myanimelist.net/images/characters/7/81310.jpg',
  },
];

async function runEnrichment() {
  const supabase = createAdminClient();

  // Clean duplicate Sanji
  const { data: sanjiList } = await supabase.from('characters').select('id, name, slug').ilike('name', '%Sanji%');
  if (sanjiList && sanjiList.length > 1) {
    const extraSanji = sanjiList.filter(s => s.name === 'Vinsmoke Sanji');
    for (const extra of extraSanji) {
      console.log(`Cleaning extra Sanji record: ${extra.name} (${extra.id})`);
      await supabase.from('character_affiliations').delete().eq('character_id', extra.id);
      await supabase.from('character_occupations').delete().eq('character_id', extra.id);
      await supabase.from('character_haki').delete().eq('character_id', extra.id);
      await supabase.from('character_aliases').delete().eq('character_id', extra.id);
      await supabase.from('character_field_evidence').delete().eq('character_id', extra.id);
      await supabase.from('characters').delete().eq('id', extra.id);
    }
  }

  for (const fact of FAMOUS_CHARACTERS) {
    const slug = fact.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    
    // Find existing by exact name first, then slug
    let { data: existing } = await supabase
      .from('characters')
      .select('id, name, slug')
      .eq('name', fact.name)
      .maybeSingle();

    if (!existing) {
      const { data: bySlug } = await supabase
        .from('characters')
        .select('id, name, slug')
        .eq('slug', slug)
        .maybeSingle();
      existing = bySlug;
    }

    let charId: string;

    const charPayload = {
      name: fact.name,
      japanese_name: fact.japanese_name,
      romanized_name: fact.romanized_name,
      slug: existing?.slug || slug,
      gender: fact.gender,
      race: fact.race,
      status: fact.status,
      age: fact.age,
      height: fact.height,
      bounty: fact.bounty,
      origin: fact.origin,
      first_appearance: fact.first_appearance,
      first_arc: fact.first_arc,
      devil_fruit_name: fact.devil_fruit_name,
      devil_fruit_type: fact.devil_fruit_type,
      devil_fruit_model: fact.devil_fruit_model || null,
      image_url: fact.image_url,
      verification_status: 'verified',
      updated_at: new Date().toISOString(),
    };

    if (existing) {
      charId = existing.id;
      const { error: updErr } = await supabase
        .from('characters')
        .update(charPayload)
        .eq('id', charId);
      if (updErr) {
        console.error(`Error updating ${fact.name}:`, updErr.message);
        continue;
      }
    } else {
      const { data: inserted, error: insErr } = await supabase
        .from('characters')
        .insert(charPayload)
        .select('id')
        .single();
      if (insErr || !inserted) {
        console.error(`Error inserting ${fact.name}:`, insErr?.message);
        continue;
      }
      charId = inserted.id;
    }

    // Affiliations
    if (fact.affiliations && fact.affiliations.length > 0) {
      await supabase.from('character_affiliations').delete().eq('character_id', charId);
      await supabase
        .from('character_affiliations')
        .insert(fact.affiliations.map((a) => ({ character_id: charId, affiliation: a })));
    }

    // Occupations
    if (fact.occupations && fact.occupations.length > 0) {
      await supabase.from('character_occupations').delete().eq('character_id', charId);
      await supabase
        .from('character_occupations')
        .insert(fact.occupations.map((o) => ({ character_id: charId, occupation: o })));
    }

    // Haki
    if (fact.haki) {
      await supabase.from('character_haki').delete().eq('character_id', charId);
      if (fact.haki.length > 0) {
        await supabase
          .from('character_haki')
          .insert(fact.haki.map((h) => ({ character_id: charId, haki_type: h })));
      }
    }

    // Aliases
    if (fact.aliases && fact.aliases.length > 0) {
      await supabase.from('character_aliases').delete().eq('character_id', charId);
      await supabase
        .from('character_aliases')
        .insert(fact.aliases.map((alias) => ({ character_id: charId, alias, alias_type: 'alias' })));
    }

    console.log(`✓ Synchronized ${fact.name} (Bounty: ${fact.bounty ? fact.bounty.toLocaleString() : 'N/A'}, Age: ${fact.age}, Height: ${fact.height}cm, Debut: ${fact.first_appearance} (${fact.first_arc}))`);
  }

  console.log('\n=== COMPLETED FAMOUS CHARACTERS ENRICHMENT ===');
  process.exit(0);
}

runEnrichment().catch(console.error);
